### ISSUE TITLE
There is no option of blog

### ISSUE THREAD

**Issue by imskr** [CodyJasonBennett/Portfolio-Website#18]
* Is there any blog page?

**Comment by CodyJasonBennett** [comment]
I have the blog currently commented out from routing in [src/app/index.js](https://github.com/CodyJasonBennett/Portfolio-Website/blob/master/src/app/index.js).

See [src/pages/Articles/](https://github.com/CodyJasonBennett/Portfolio-Website/tree/master/src/pages/Articles) and [src/posts](https://github.com/CodyJasonBennett/Portfolio-Website/tree/master/src/posts) for article components and content, respectively.

If you have any suggestions for any articles or issues for me to write on, please let me know.
I intend to populate it with design and development articles.

**Comment by imskr** [comment]
That's awesome and cool. How you designed your logo? any tool?

**Comment by CodyJasonBennett** [comment]
I've used Illustrator in the past but more recently do simple vectors within Figma.

I also have this site's design tools and stack outlined in [public/humans.txt](https://github.com/CodyJasonBennett/Portfolio-Website/blob/master/public/humans.txt) with its component-based design system [here](https://storybook.codyb.co).

I'll look to cover less trivial design and development tensions as time allows.

I hope this helps.
